all:
  hosts:
    kubernetes.damonjebb.local:
      ansible_host: 192.168.100.12
  children:
    kube-masters:
      hosts:
        pi1:
          ansible_host: 192.168.100.12
    kube-nodes:
      hosts:
        pi2:
          ansible_host: 192.168.100.13

#[kube-masters]
#pi1 ansible_host=92.168.100.12 ansible_ssh_user root

#[kube-nodes]
#pi2 ansible_host=192.168.100.13 ansible_ssh_user=root

#[ubuntu:children]
#kube-masters
#kube-nodes
