- hosts: kube_masters[0]
  gather_facts: no

  tasks:
    - name: get join command
      command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: no

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kube_nodes
  become: yes

  vars:
    join_command: "{{ hostvars['pi1'].join_command }}"
    ansible_ssh_user: "{{ super_user }}"
  roles:
    - ssh
    - hosts
    - kube-dependencies
    - kube-node-init
